// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"genericserr/ent/migrate"

	"genericserr/ent/tester"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Tester is the client for interacting with the Tester builders.
	Tester *TesterClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Tester = NewTesterClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Tester: NewTesterClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Tester: NewTesterClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Tester.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Tester.Use(hooks...)
}

// TesterClient is a client for the Tester schema.
type TesterClient struct {
	config
}

// NewTesterClient returns a client for the Tester from the given config.
func NewTesterClient(c config) *TesterClient {
	return &TesterClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tester.Hooks(f(g(h())))`.
func (c *TesterClient) Use(hooks ...Hook) {
	c.hooks.Tester = append(c.hooks.Tester, hooks...)
}

// Create returns a create builder for Tester.
func (c *TesterClient) Create() *TesterCreate {
	mutation := newTesterMutation(c.config, OpCreate)
	return &TesterCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Tester entities.
func (c *TesterClient) CreateBulk(builders ...*TesterCreate) *TesterCreateBulk {
	return &TesterCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Tester.
func (c *TesterClient) Update() *TesterUpdate {
	mutation := newTesterMutation(c.config, OpUpdate)
	return &TesterUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TesterClient) UpdateOne(t *Tester) *TesterUpdateOne {
	mutation := newTesterMutation(c.config, OpUpdateOne, withTester(t))
	return &TesterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TesterClient) UpdateOneID(id int) *TesterUpdateOne {
	mutation := newTesterMutation(c.config, OpUpdateOne, withTesterID(id))
	return &TesterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Tester.
func (c *TesterClient) Delete() *TesterDelete {
	mutation := newTesterMutation(c.config, OpDelete)
	return &TesterDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *TesterClient) DeleteOne(t *Tester) *TesterDeleteOne {
	return c.DeleteOneID(t.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *TesterClient) DeleteOneID(id int) *TesterDeleteOne {
	builder := c.Delete().Where(tester.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TesterDeleteOne{builder}
}

// Query returns a query builder for Tester.
func (c *TesterClient) Query() *TesterQuery {
	return &TesterQuery{
		config: c.config,
	}
}

// Get returns a Tester entity by its id.
func (c *TesterClient) Get(ctx context.Context, id int) (*Tester, error) {
	return c.Query().Where(tester.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TesterClient) GetX(ctx context.Context, id int) *Tester {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TesterClient) Hooks() []Hook {
	hooks := c.hooks.Tester
	return append(hooks[:len(hooks):len(hooks)], tester.Hooks[:]...)
}
