// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TestersColumns holds the columns for the "testers" table.
	TestersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "age", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// TestersTable holds the schema information for the "testers" table.
	TestersTable = &schema.Table{
		Name:       "testers",
		Columns:    TestersColumns,
		PrimaryKey: []*schema.Column{TestersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TestersTable,
	}
)

func init() {
}
